# fly.toml file generated for deumbrellization-todo-web on 2023-02-21T22:40:16+01:00

app = "deumbrellization-todo-web"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  PHX_HOST = "deumbrellization-todo-web.fly.dev"
  PORT = "8080"
  RELEASE_COOKIE = "DQ6LxZxeCk4rf-06xahNm1LYm5BOhnDUIE8JUv9PmYx0ckMe7tCkqQ"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
